"""empty message

Revision ID: 470c6035fb0c
Revises: 
Create Date: 2018-11-03 23:27:48.850222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470c6035fb0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('gram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gram_id'], ['gram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('gram')
    # ### end Alembic commands ###
